version: '3.1' 

services:
  any23-server-docker:
    container_name: any23-server-docker
    image: openkbs/any23-server-docker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - CONTAINER_NAME=any23-server-docker
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      # - APP_HOME=${APP_HOME:-/home/developer/app}
      # - APP_MAIN=${APP_MAIN:-setup.sh}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-127.0.0.1}
      - DOCKER_HOST_NAME=${DOCKER_HOST_NAME:-localhost}
    volumes:
      - ./workspace:/home/developer/workspace
      - ./data:/home/developer/data
    volumes:
      ## ==== Common mapping ====
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./certificates:/home/developer/certificates
      ## ==== Use $HOME/data-docker as base directory: ====
      #- $HOME/data-docker/any23-server-docker/data:/home/developer/data
      #- $HOME/data-docker/any23-server-docker/workspace:/home/developer/workspace
      ## ==== Use current directory as root for mapping Volumes ====
      ## (You need to manually create those child directory: ./data, ./workspace, and others)
      - ./data:/home/developer/data
      - ./workspace:/home/developer/workspace
 
    ## -------------------------------
    ## -- Change to your specific port
    ## -------------------------------
    # ports:
    #   - "12345:12345"

    ## -----------------------------
    ## -- Network setup if needed --
    ## -----------------------------
    # networks:
    #  - dev_network

#networks:
#  dev_network:
#    external:
#      name: dev_network


